version: "3.8"

services:
  www:
    build:
      context: .
      dockerfile: ./php/extensions_php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

  composer:
    image: composer:2.1.9
    entrypoint: composer
    volumes:
      - .:/app

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  dev: