version: "3.8"

services:
## PHP - NPM
  www:
    build:
      dockerfile: ./php/extensions_php
    container_name: php_fa
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    #restart: always
    networks:
      - dev

## Composer
  composer:
    container_name: composer_fa
    image: composer:2.1.9
    entrypoint: ["composer", "install", "--no-interaction"]
    volumes:
      - .:/app

## MY SQL
  db:
    container_name: mysql_fa
    image: mysql:5.6
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./datavolume:/var/lib/mysql:rw
    ports:
      - 3306:3306

## ADMINER
  adminer:
    container_name: adminer_fa
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  datavolume:

networks:
  dev: