version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./php/extensions_php
    ports:
      - 8741:80
    volumes:
      - ./:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db_mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=symfony
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db

networks:
  dev: